version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3  # Garantir que o banco SQLite seja persistente
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - DEBUG=True
      - USE_SQLITE=True