# Generated by Django 4.2 on 2025-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50, verbose_name='Espécie do Animal')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do Animal')),
                ('raca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça')),
                ('idade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idade Aproximada')),
                ('Descricao_animal', models.TextField(verbose_name='Descrição do Animal')),
                ('local', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Caso')),
                ('tipo_maustratos', models.CharField(choices=[('Abandono', 'Abandono'), ('Negligencia', 'Negligência'), ('Violencia Fisica', 'Violencia Fisica'), ('Trabalho Forçado', 'Trabalho Forçado'), ('Alimentacao Inadequada', 'Alimentação Inadequada'), ('Outros', 'Outros')], max_length=200, verbose_name='Tipo de Maus-Tratos')),
                ('descricao_caso', models.TextField(verbose_name='Descrição detalhada dos Maus-Tratos')),
                ('responsavel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome do responsável pelo animal')),
                ('comprovacao', models.FileField(blank=True, null=True, upload_to='comprovacoes/', verbose_name='Anexe fotos ou vídeos')),
                ('nome_denunciante', models.CharField(blank=True, help_text='Sua identificação não é obrigatória, identifiqu-se apenas se quiser!', max_length=100, null=True, verbose_name='Nome do Denunciante')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('data_denuncia', models.DateTimeField(auto_now_add=True, verbose_name='Data da Denúncia')),
            ],
        ),
    ]
