# Generated by Django 4.2 on 2025-03-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_maustratos',
            field=models.TextField(choices=[('Abandono', 'Abandono'), ('Negligencia', 'Negligência'), ('Violencia Fisica', 'Violencia Fisica'), ('Trabalho Forçado', 'Trabalho Forçado'), ('Alimentacao Inadequada', 'Alimentação Inadequada'), ('Outros', 'Outros')], max_length=200, verbose_name='Tipo de Maus-Tratos'),
        ),
    ]
