# Generated by Django 4.2 on 2025-03-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_alter_denuncia_tipo_maustratos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-data_denuncia'], 'verbose_name': 'Denúncia', 'verbose_name_plural': 'Denúncias'},
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='Descricao_animal',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='comprovacao',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='imagens',
            field=models.FileField(blank=True, null=True, upload_to='comprovacao/', verbose_name='Anexe fotos ou vídeos'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo_maustratos',
            field=models.TextField(verbose_name='Tipo de Maus-Tratos'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='descricao_animal',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Animal'),
        ),
    ]
