# Generated by Django 4.2 on 2025-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_alter_denuncia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='comprovacao/', verbose_name='Anexe fotos ou vídeos'),
        ),
    ]
