# Generated by Django 4.2 on 2025-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_alter_denuncia_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Anexe fotos ou vídeos'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='nome_denunciante',
            field=models.CharField(blank=True, help_text='Sua identificação não é obrigatória, identifique-se apenas se quiser!', max_length=100, null=True, verbose_name='Nome do Denunciante'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome ou características do responsável pelo animal'),
        ),
    ]
