# Generated by Django 4.2 on 2025-04-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_alter_denuncia_imagens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('processando', 'Processando'), ('tratada', 'Tratada'), ('cancelada', 'Cancelada')], default='recebida', max_length=20, verbose_name='Status'),
        ),
    ]
