# Generated by Django 4.2 on 2025-04-21 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comum', '0006_denuncia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='atendente_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente Responsável'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='data_atribuicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atribuição'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='imagens',
            field=models.FileField(blank=True, null=True, upload_to='comprovacoes/', verbose_name='Anexe fotos ou vídeos'),
        ),
        migrations.CreateModel(
            name='Tratativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Tratativa')),
                ('data_tratativa', models.DateTimeField(auto_now_add=True, verbose_name='Data da Tratativa')),
                ('status_anterior', models.CharField(choices=[('recebida', 'Recebida'), ('processando', 'Processando'), ('tratada', 'Tratada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('status_novo', models.CharField(choices=[('recebida', 'Recebida'), ('processando', 'Processando'), ('tratada', 'Tratada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratativas', to='comum.denuncia')),
            ],
            options={
                'verbose_name': 'Tratativa',
                'verbose_name_plural': 'Tratativas',
                'ordering': ['-data_tratativa'],
            },
        ),
    ]
